name: build-and-push-api

on:
  push:
    paths:
      - 'apps/api/**'
      - '.github/workflows/build_api.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # GHCR requires lowercase owner in the image name
      - name: Lowercase org
        run: echo "ORG_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORG_LC }}/sprintboard-api:latest
            ghcr.io/${{ env.ORG_LC }}/sprintboard-api:sha-${{ github.sha }}
