name: build-and-push-frontend
on:
  push:
    paths: ["apps/frontend/**",".github/workflows/build_frontend.yml"]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sprintboard-frontend
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest -f apps/frontend/Dockerfile apps/frontend
      - name: Push
        run: docker push $IMAGE_NAME --all-tags
