      - name: Set env (lowercase owner + short sha)
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: apps/frontend
          file: apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/sprintboard-frontend:latest
            ghcr.io/${{ env.OWNER }}/sprintboard-frontend:sha-${{ env.SHORT_SHA }}
          build-args: |
            NEXT_PUBLIC_API_BASE=http://3.110.63.62:30081

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/sprintboard-api:latest
            ghcr.io/${{ env.OWNER }}/sprintboard-api:sha-${{ env.SHORT_SHA }}
