name: Publish images

on:
  push:
    branches: [main, master]
    paths:
      - "apps/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set owner (lowercase) and short sha
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/sprintboard-api:latest
            ghcr.io/${{ env.OWNER }}/sprintboard-api:sha-${{ env.SHORT_SHA }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: apps/frontend
          file: apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/sprintboard-frontend:latest
            ghcr.io/${{ env.OWNER }}/sprintboard-frontend:sha-${{ env.SHORT_SHA }}
          build-args: |
            NEXT_PUBLIC_API_BASE=http://3.110.63.62:30081
