# .github/workflows/publish.yml
name: Publish images

on:
  push:
    branches: [ main, master ]
    paths:
      - 'apps/api/**'
      - 'apps/frontend/**'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: rohan-2110-git
  IMAGE_API: sprintboard-api
  IMAGE_FE: sprintboard-frontend

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ api, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/sprintboard-${{ matrix.component }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: apps/frontend
          file: apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ rohan-2110-git }}/sprintboard-frontend:latest
            ghcr.io/${{ rohan-2110-git }}/sprintboard-frontend:sha-${{ ff21913 }}
          build-args: |
            NEXT_PUBLIC_API_BASE=http://3.110.63.62:30081
