name: publish

on:
  push:
    branches: [ master, main ]
    paths:
      - "apps/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  api:
    name: Build & Push API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner for GHCR
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sprintboard-api:latest
            ghcr.io/${{ env.OWNER_LC }}/sprintboard-api:sha-${{ github.sha }}

  frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner for GHCR
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"
          # Bake API base at build time for Next.js
          echo "NEXT_PUBLIC_API_BASE=http://3.110.63.62:30081" >> "$GITHUB_ENV"

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_BASE=${{ env.NEXT_PUBLIC_API_BASE }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sprintboard-frontend:latest
            ghcr.io/${{ env.OWNER_LC }}/sprintboard-frontend:sha-${{ github.sha }}
