name: Publish images to GHCR

on:
  push:
    branches: [ "master" ]
    paths:
      - "apps/api/**"
      - "apps/frontend/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

# Keep everything lowercase for GHCR tags
env:
  ORG: rohan-2110-git
  IMAGE_API: ghcr.io/rohan-2110-git/sprintboard-api
  IMAGE_FE: ghcr.io/rohan-2110-git/sprintboard-frontend

  # The API URL that the browser will call (baked into the FE build)
  NEXT_PUBLIC_API_BASE: http://3.110.63.62:30081

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show workspace tree (debug helper)
        run: |
          pwd
          ls -la
          ls -la apps || true
          ls -la apps/api || true
          ls -la apps/frontend || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.ORG }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sprintboard-api:latest
            ghcr.io/${{ github.repository_owner }}/sprintboard-api:sha-${{ github.sha }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_BASE=http://3.110.63.62:30081
          tags: |
            ${{ env.IMAGE_FE }}:latest
            ${{ env.IMAGE_FE }}:sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=sprintboard-frontend
            org.opencontainers.image.description=sprintboard
